# Generated by Django 4.2 on 2023-04-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vacancy_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='user',
        ),
    ]
